export const projects = [
  {
    id: nanoid(),
    title: 'Phonebook',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook2',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook3',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook4',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook5',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook6',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook7',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
  {
    id: nanoid(),
    title: 'Phonebook8',
    img: '',
    description: 'Phonebook app helps you save phone contacts and manage them',
    technologies: ['React.js'],
    github: 'https://github',
    live: 'https://',
  },
];
